name: CI/CD Pipeline
on:
  push:
    branches:
      - main
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build Docker image
        # Build the image and tag it with your DockerHub username and repository
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/stylesprint:latest .
      - name: Run tests in verbose mode
        # Run the tests using the built image
        run: docker run ${{ secrets.DOCKER_USERNAME }}/stylesprint:latest pytest -v
  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to DockerHub
        # Log in to DockerHub using secrets
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Push Docker image
        # Push the image to DockerHub with the tag latest
        run: docker push ${{ secrets.DOCKER_USERNAME }}/stylesprint:latest
